account/urls.py
from django.urls import path
from account.views import *

app_name = 'account'
urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    # path('<int:pk>/', UserDetailView.as_view(), name='detail'),
]

core/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static 
from django.conf import settings
from . import views
from .views import *


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('delivery', DeliveryPage.as_view(), name='delivery'),
    path('s/', SearchList.as_view(), name='search'),
    
    # path('s/', search_bar, name='search')  
]

flower_shop/urls.py
from django.contrib import admin
from django.urls import include, path
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('flowercare/', include('flowercare.urls')),
    path('campaign/', include('campaign.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:

    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Букеты из роз': 'flower__count',
        'Цветы в горшках': 'flowerinpot__count',
        'Свадебные букеты': 'weddingflower__count',
        'Другие виды цветов': 'otherflower__count',
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('flower', 'flowerinpot', 'weddingflower', 'otherflower')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')


    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()



class Flower(Product):

    quantity = models.IntegerField(default=0, verbose_name='Количество роз в букете')
    size = models.IntegerField(blank=True, default=0, verbose_name='Высота/Длина')
    greeting_card = models.CharField(max_length=100, verbose_name='Наличие поздравителной карты')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class WeddingFlower(Product):

    size = models.IntegerField(blank=True, default=0, verbose_name='Высота/Длина')
    butonniere = models.CharField(max_length=255, verbose_name='Бутоньерка')
    b_image = models.ImageField(blank=True, verbose_name='Фото бутоньерки')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class OtherFlower(Product):

    size = models.IntegerField(blank=True, default=0, verbose_name='Высота/Длина')
    greeting_card = models.CharField(max_length=100, verbose_name='Наличие поздравителной карты')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Flowerinpot(Product):

    size = models.IntegerField(blank=True, default=0, verbose_name='Высота/Длина')
    greeting_card = models.CharField(max_length=100, verbose_name='Наличие поздравителной карты')
    pot_size = models.CharField(
        max_length=255, null=True, blank=True, verbose_name='Размер цветочного горшка'
    )
    pot_color = models.CharField(max_length=255, verbose_name='Цвет горшка')
    grooming_instructions = models.CharField(max_length=255, verbose_name='Инструкция по уходу')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_order')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказа',
        choices=STATUS_CHOICES,

        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

core/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )

core/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_greeting_card').on('click', function(){
        if($('#id_greeting_card').prop('checked') == true){
            $('#id_pot_size').prop('readonly', false)
            $('#id_pot_size').val('')
            $('#id_pot_size').css('background', 'white')
        }else{
            $('#id_pot_size').prop('readonly', true)
            $('#id_pot_size').val('')
            $('#id_pot_size').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

core/templates/cart.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
  <h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста{% endif %}</h3>
{% else %}
  <h5>Зарегистрируйтесь чтобы добавлять в корзину, либо войдите в свой аккаунт</h5>
  <a href="{% url 'account:register' %}"><p>Регистрация</p></a>
  
  <a href="{% url 'account:login' %}"><p>Войти</p></a>
{% endif %}
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
        <th scope="col">Общая цена</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
          <td>{{ item.content_object.price }} Сом</td>
          <td>
            <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="POST">
              {% csrf_token %}
              <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
              <br>
              <input type="submit" class="btn btn-primary" value="Изменить кол-во">
            </form>
          </td>
            <td>{{ item.final_price }} Сом</td>
          <td>
            <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
          </td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} сом.</strong></td>
          <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
        </tr>
  </tbody>
</table>
{% endif %}
{% endblock content %}

core/templates/category_detail.html
{% extends 'base.html' %}


{% block content %}
    <nav aria-label="breadcrumb" class="mt-3">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item active">{{ category.name }}</li>
      </ol>
    </nav>
<div class="row">
  {% for product in category_products %}
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
      <div class="card-body">
        <h5 class="card-title">
          <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        </h5>
        <h6>{{ product.price }} Сом</h6>
        <!--rating-->
    <style>
      * {
      margin: 0;
      padding: 0;
    }
    .rate {
      float: left;
      height: 46px;
      padding: 0 10px;
    }
    .rate:not(:checked) > input {
      position: absolute;
      top: -9999px;
    }
    .rate:not(:checked) > label {
      float: right;
      width: 1em;
      overflow: hidden;
      white-space: nowrap;
      cursor: pointer;
      font-size: 30px;
      color: #ccc;
    }
    .rate:not(:checked) > label:before {
      content: "★ ";
    }
    .rate > input:checked ~ label {
      color: #ffc700;
    }
    .rate:not(:checked) > label:hover,
    .rate:not(:checked) > label:hover ~ label {
      color: #deb217;
    }
    .rate > input:checked + label:hover,
    .rate > input:checked + label:hover ~ label,
    .rate > input:checked ~ label:hover,
    .rate > input:checked ~ label:hover ~ label,
    .rate > label:hover ~ input:checked ~ label {
      color: #c59b08;
    }
    </style>
    
        <div class="rate" style="margin: 0;">
          <input type="radio" id="star5" name="rate" value="5" />
          <label for="star5" title="text">5 stars</label>
          <input type="radio" id="star4" name="rate" value="4" />
          <label for="star4" title="text">4 stars</label>
          <input type="radio" id="star3" name="rate" value="3" />
          <label for="star3" title="text">3 stars</label>
          <input type="radio" id="star2" name="rate" value="2" />
          <label for="star2" title="text">2 stars</label>
          <input type="radio" id="star1" name="rate" value="1" />
          <label for="star1" title="text">1 star</label>
        </div>
    <!--end of rating-->
              <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
      <button class="btn btn-success">Добавить в корзину</button>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

core/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
        <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
          <td>{{ item.content_object.price }} сом.</td>
          <td>{{ item.qty }}</td>
            <td>{{ item.final_price }} сом.</td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} сом.</strong></td>
        </tr>
  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-success btn-block mb-3" values="Оформить заказ">
</form>
{% endblock content %}

core/templates/flower_specification.html
<table class="table">
    <tbody>
      <tr>
        <td>Размер</td>
        <td>{{ product.size }}</td>
      </tr>
    </tbody>
  </table>
  

core/templates/flowerinpot_specification.html
<table class="table">
    <tbody>
      <tr>
        <td>Высота растения с учетом горшка</td>
        <td>{{ product.size }}</td>
      </tr>
        <tr>
        <td>Наличие поздравительной карты</td>
        <td>{{ product.greeting_card }}</td>
      <tr>
        <td>Размер цветочного горшка</td>
        <td>{{ product.pot_size }}</td>
      </tr>
      <tr>
        <td>Цвет горшка</td>
        <td>{{ product.pot_color }}</td>
      </tr>
      <tr>
        <td>Инструкция по уходу</td>
        <td>{{ product.grooming_instructions }}</td>
      </tr>
    </tbody>
  </table>
  

core/templates/otherflower_spec.html
<table class="table">
    <tbody>
        <tr>
            <td>Длина букета</td>
            <td>{{ product.size }}</td>
        </tr>
        <tr>
            <td>Наличие поздравительной карты</td>
            <td>{{ product.greeting_card }}</td>
       
    </tbody>
  </table>

core/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
<link rel="stylesheet" type="text/css" href="styles.css">
    <nav aria-label="breadcrumb" class="mt-3">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
      </ol>
    </nav>

<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" class="img-fluid">
        <hr>
        {% if product.b_image %}
        <img src="{{ product.b_image.url }}" class="img-fluid">
        {% endif %}
    </div>
    <div class="col-md-8">

        <h3>{{ product.title }}</h3>
        
 <!--rating-->
    <style>
      * {
      margin: 0;
      padding: 0;
    }
    .rate {
      float: left;
      height: 46px;
      padding: 0 10px;
    }
    .rate:not(:checked) > input {
      position: absolute;
      top: -9999px;
    }
    .rate:not(:checked) > label {
      float: right;
      width: 1em;
      overflow: hidden;
      white-space: nowrap;
      cursor: pointer;
      font-size: 30px;
      color: #ccc;
    }
    .rate:not(:checked) > label:before {
      content: "★ ";
    }
    .rate > input:checked ~ label {
      color: #ffc700;
    }
    .rate:not(:checked) > label:hover,
    .rate:not(:checked) > label:hover ~ label {
      color: #deb217;
    }
    .rate > input:checked + label:hover,
    .rate > input:checked + label:hover ~ label,
    .rate > input:checked ~ label:hover,
    .rate > input:checked ~ label:hover ~ label,
    .rate > label:hover ~ input:checked ~ label {
      color: #c59b08;
    }
    </style>
    
        <div class="rate" style="margin: 0;">
          <input type="radio" id="star5" name="rate" value="5" />
          <label for="star5" title="text">5 stars</label>
          <input type="radio" id="star4" name="rate" value="4" />
          <label for="star4" title="text">4 stars</label>
          <input type="radio" id="star3" name="rate" value="3" />
          <label for="star3" title="text">3 stars</label>
          <input type="radio" id="star2" name="rate" value="2" />
          <label for="star2" title="text">2 stars</label>
          <input type="radio" id="star1" name="rate" value="1" />
          <label for="star1" title="text">1 star</label>
        </div>
    <!--end of rating--> 
    <br>
        <br><p style="font-weight: bolder; color: rgb(214, 29, 29);">Цена: {{ product.price }} Сом</p>
        <p><p style="font-weight: 500;">Описание:</p>{{ product.description }}</p>
        <hr>
        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-info">Добавить в корзину</button></a>
    </div>
    <p class="mt-4" style="font-weight: bolder;">Характеристика:</p>

    {{ product|product_spec }}

<!--Review part-->
<div class="container">

  <ul class="nav tabs-primary nav-justified" id="advancedTab" role="tablist">
    
    <li class="nav-item">
      <h4>Отзывы на товар</h4>


      {{ date_added}}
     
      <p>{{ content }}</p>
    </li>
    
  </ul>
  
    
  <div class="" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
     
      {% if request.user.is_authenticated %}
      <h5 class="mt-4">Оставьте свой отзыв о нашем товаре</h5>
  
      <div> 
        <!-- Your review -->
        <div class="md-form md-outline">
          <form method="POST" action=".">
            {% csrf_token %}
           
            <input type="text" class="form-control" rows="5" placeholder="Текст Вашего отзыва">
            {{ date_added }}
            <div class="control">
              <br><button type="button" class="btn btn-info">Отправить</button><br>
            </div> 
          
          </form>
          
        </div>
       
        
      {% else %}
      <p>Зарегистрируйтесь для того, чтобы оставлять отзывы</p>
      {% endif %}
    </div>
 

</div> 
<!-- Classic tabs -->


  </div>

  <br><br>
  <!-- <style>
    .notification.space-below {
      margin-bottom: 20px;
    }
  </style>
    
  <h3 class="subtitle" style="text-align: center;">Отзывы:</h3>
  <div class="reviews-wrapper">
    {% for review in product.reviews.all %}
      <div class="notification space-below">
        <p>
          <strong>Дата: </strong> {{ review.date_added|date:"d-m-Y" }},
          <strong>Оценка: </strong>{{ review.stars }}
        </p>
          {{ review.content }}
      </div>
      {% empty %}
    
        <div class="notification space-below">Нет отзывов...</div>
    
      
    {% endfor %}
  </div>
  <div class="notification space-below">
    {% if request.user.is_authenticated %}
      <form method="POST" action=".">
        {% csrf_token %}
        {{ review_form }}
        <div class="field">
          <label>Оценка</label>
          <div class="control">
            <div class="select" data-mdb-toggle="rating">
              <select name="stars" data-mdb-toggle="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3" selected>3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
          </div>
        </div>

        <div class="field">
         
          <div class="form-group">
            <textarea class="form-control" id="exampleFormControlTextarea1" name="content" placeholder="Текст отзыва"></textarea>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <button class="btn btn-info">Отправить</button>
          </div>
        </div>

      </form>
    {% else %}
      <p>Зарегистрируйтесь или войдите в свой аккаунт, чтобы оставить отзыв</p>
    {% endif %}

  </div> -->

</div>

{% endblock content %}

core/templates/search.html
{% extends 'base.html' %}

{% block content %}

<h3>Найдено по Вашему запросу:</h3>
<br/>
<h5>{{ query }}</h5>
{{ goods }}
{{ products }}
{% endblock content %}

core/templates/weddingflower_specif.html
<table class="table">
    <tbody>
        <tr>
            <td>Длина букета</td>
            <td>{{ product.size }}</td>
        </tr>
        <tr>
            <td>Бутоньерка</td>
            <td>{{ product.butonniere }}</td>
       
    </tbody>
  </table>